wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.12/apache-maven-3.9.12-bin.zip
distributionSha256Sum=b4880f2e48ece5b4a959c1f87f893b29b27f8e4e3dfd4c2bc72dae4f5e42f61f
