quarkus.datasource.db-kind=${DB_KIND:mysql}
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:none}
quarkus.datasource.jdbc.url=${DB_JDBC_URL:none}

quarkus.hibernate-orm.schema-management.strategy=${DB_SCHEMA_STRATEGY:update}

# Firebase admin SDK - path to service account JSON (mount as secret / volume)
firebase.service-account=${FIREBASE_SERVICE_ACCOUNT_LOCATION:none}
app.name=decision360
app.version=${APP_VERSION:dev}

quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}


%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=leote
%test.quarkus.datasource.password=
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=no-file
%test.firebase.service-account-location=none

quarkus.hibernate-orm.log.sql = true
quarkus.hibernate-orm.log.format-sql = true
quarkus.hibernate-orm.log.bind-parameters = false

